POST http://localhost:8090/checkout/api/checkout
Content-Type: application/json

{
  "cartId": "4222c1d9-036d-4a32-9caa-caa69b6bc9a7"
}

<> 2023-05-05T181037.200.html
<> 2023-05-05T180957.500.html
<> 2023-05-05T180919.500.html

###

POST http://localhost:8090/checkout/api/checkout/8ebc790b-f34a-4a5c-bbc5-dbb661eb57f9/customer
Content-Type: application/json

{
  "email": "lorem@dolor.sit",
  "lastName": "asdf",
  "firstName": "osidjf",
  "phone": "osidfjosidjf"
}

###

POST http://localhost:8090/checkout/api/checkout/8ebc790b-f34a-4a5c-bbc5-dbb661eb57f9/payment-address
Content-Type: application/json

{
  "country": "HU",
  "postcode": "1234",
  "city": "Gotham",
  "address": "Some str 123"
}

###

POST http://localhost:8090/checkout/api/checkout/8ebc790b-f34a-4a5c-bbc5-dbb661eb57f9/shipping-address
Content-Type: application/json

{
  "country": "HU",
  "postcode": "1234",
  "city": "Gotham",
  "address": "Some str 123"
}

<> 2023-05-05T181616.500.html
<> 2023-05-05T181315.500.html

###

GET http://localhost:8090/checkout/api/checkout/89a46369-a0d2-42cd-929f-592f4f469406
Content-Type: application/json


###

POST http://localhost:8090/checkout/api/checkout/8ebc790b-f34a-4a5c-bbc5-dbb661eb57f9/confirm
Content-Type: application/json

###

POST http://localhost:8090/checkout/api/checkout/8ebc790b-f34a-4a5c-bbc5-dbb661eb57f9/payment-method
Content-Type: application/json

{
  "paymentMethodId": "5217588b-97e5-4bec-9e6c-1716397d4d3f"
}

###

POST http://localhost:8090/checkout/api/checkout/8ebc790b-f34a-4a5c-bbc5-dbb661eb57f9/shipping-method
Content-Type: application/json

{
  "shippingMethodId": "1b9d6bcd-bbfd-4b2d-9b5d-ab8dfbbd4bed"
}

###

POST http://localhost:8090/payment/api/payment/initiate
Content-Type: application/json

{
"paymentMethodId": "5217588b-97e5-4bec-9e6c-1716397d4d3f",
"customer": {
"email": "test@test.hu",
"billingAddress": {
"country": "Magyarország",
"city": "Budapest",
"zipCode": "1111",
"address": "Teszt utca 1.",
"companyName": "Teszt Kft.",
"taxNumber": "12345678-1-11"
}
},
"amount": 10000
}

###

GET http://localhost:8090/payment/api/paymentMethod/5217588b-97e5-4bec-9e6c-1716397d4d3f