<?php

namespace App\Infrastructure\Persistence\Doctrine\Type;

use App\Domain\Shared\EntityId;
use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Types\BinaryType;
use Ramsey\Uuid\Uuid;

class EntityIdType extends BinaryType
{
    public function convertToDatabaseValue($value, AbstractPlatform $platform)
    {
        return parent::convertToDatabaseValue($value, $platform); // TODO: Change the autogenerated stub
    }

    public function convertToPHPValue($value, AbstractPlatform $platform)
    {
        return new EntityId(Uuid::fromBytes($value));
    }

    public function getName()
    {
        return 'entity_id';
    }

}